"""Structured audit logging for FloorMind agent interactions.

Logs every question, SQL generation, validation result, and execution as JSONL.
Stored at logs/audit.jsonl for BRC traceability and security auditing.

Inspired by PyCon DE 2026: "Building Secure Environments for CLI Code Agents" (Nezbeda).
The pattern: log every agent decision so you can audit what happened and why.

Each line is a JSON object with:
- timestamp (ISO 8601, UTC)
- event (question_asked | sql_generated | sql_validated | sql_executed | llm_call)
- plus event-specific fields

Use with jq, Datasette, or any JSONL-compatible tool:
    cat logs/audit.jsonl | jq 'select(.event == "sql_executed" and .error != null)'
"""
from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

LOG_DIR = Path(os.getenv("FLOORMIND_LOG_DIR", "logs"))
LOG_DIR.mkdir(exist_ok=True, parents=True)
AUDIT_FILE = LOG_DIR / "audit.jsonl"

log = logging.getLogger("audit")


def log_event(event_type: str, **fields: Any) -> None:
    """Append a structured event to the audit log.

    Failures are logged but never raise — auditing must not block the agent.
    """
    entry: dict[str, Any] = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "event": event_type,
    }
    entry.update(fields)
    try:
        with AUDIT_FILE.open("a", encoding="utf-8") as f:
            f.write(json.dumps(entry, default=str) + "\n")
    except OSError as e:
        log.warning("Audit log write failed: %s", e)


def log_question(question: str, user: str | None = None) -> None:
    """Log a user question at the start of the pipeline."""
    log_event("question_asked", question=question[:500], user=user or "anonymous")


def log_sql_generated(sql: str, domain: str, source: str) -> None:
    """Log SQL generation outcome.

    source: "library" (pre-built match) or "llm" (generated by LLM).
    """
    log_event("sql_generated", sql=sql[:1000], domain=domain, source=source)


def log_validation(passed: bool, warnings: list[str] | None = None, error: str | None = None) -> None:
    """Log SQL validation result (5-stage pipeline outcome)."""
    log_event(
        "sql_validated",
        passed=passed,
        warnings=warnings or [],
        error=error,
    )


def log_execution(
    sql: str,
    row_count: int = 0,
    duration_ms: float = 0.0,
    error: str | None = None,
) -> None:
    """Log SQL execution result against the database."""
    log_event(
        "sql_executed",
        sql=sql[:200],
        row_count=row_count,
        duration_ms=round(duration_ms, 2),
        error=error,
    )


def log_llm_call(
    model: str,
    duration_ms: float,
    prompt_tokens: int | None = None,
    completion_tokens: int | None = None,
    error: str | None = None,
) -> None:
    """Log an LLM API call for cost/latency tracking."""
    log_event(
        "llm_call",
        model=model,
        duration_ms=round(duration_ms, 2),
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        error=error,
    )


def tail(n: int = 50) -> list[dict]:
    """Return the last N audit events (for debug / UI display)."""
    if not AUDIT_FILE.exists():
        return []
    try:
        with AUDIT_FILE.open(encoding="utf-8") as f:
            lines = f.readlines()
        return [json.loads(line) for line in lines[-n:]]
    except (OSError, json.JSONDecodeError):
        return []
